version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_BUCKET_LINK: ${S3_BUCKET_LINK}
      GITHUB_EMAIL: ${GITHUB_EMAIL}
      GITHUB_NAME: ${GITHUB_NAME}
      AWS_PROFILE: ${AWS_PROFILE}
      LOAN_CSV_PATH: ${LOAN_CSV_PATH}
      PAYMENT_CSV_PATH: ${PAYMENT_CSV_PATH}
      UNDERWRITING_CSV_PATH: ${UNDERWRITING_CSV_PATH}
      MODEL_PATH: ${MODEL_PATH}
      ENCODER_PATH: ${ENCODER_PATH}
      METRICS_JSON_PATH: ${METRICS_JSON_PATH}
      TRAIN_DF_PATH: ${TRAIN_DF_PATH}
      TEST_DF_PATH: ${TEST_DF_PATH}
